// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRcMSbyh33RoqYEp8Osf9pPZEOcBep7rY',
    appId: '1:2985457361:web:78d4f1e26db22ceb5437f0',
    messagingSenderId: '2985457361',
    projectId: 'blogs-5eb57',
    authDomain: 'blogs-5eb57.firebaseapp.com',
    storageBucket: 'blogs-5eb57.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC70cnQaw5pJJ4xFuzMr-uMcOfYl7cCg0g',
    appId: '1:2985457361:android:ab1fc33cfc18e7bf5437f0',
    messagingSenderId: '2985457361',
    projectId: 'blogs-5eb57',
    storageBucket: 'blogs-5eb57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl2_lFzVbhn_d8hOAAcoFSSsqgXXAZ0EY',
    appId: '1:2985457361:ios:1032a8734aafb6925437f0',
    messagingSenderId: '2985457361',
    projectId: 'blogs-5eb57',
    storageBucket: 'blogs-5eb57.appspot.com',
    iosClientId: '2985457361-omktbal6r3ipelqqk5rd97c2f31upt1j.apps.googleusercontent.com',
    iosBundleId: 'com.example.lukcytravel',
  );
}
